-- AlterTable
ALTER TABLE "Rabbit" ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "birthDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL;
